In [1]:
import numpy as np

In [2]:
my_list=[1,3,3,4]

In [3]:
my_array1=np.array(my_list)

In [5]:
my_array1

array([1, 3, 3, 4])

In [6]:
mylist2=[4,5,6,6]

In [8]:
my_lists=[my_list,mylist2]


In [9]:
second_array=np.array(my_lists)

In [10]:
second_array


array([[1, 3, 3, 4],
       [4, 5, 6, 6]])

In [13]:
second_array.shape



(2, 4)

In [14]:
second_array.dtype

dtype('int32')

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones([5,5])


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.twos([5,8])

AttributeError: module 'numpy' has no attribute 'twos'

In [19]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
np.arange(6,200,30)

array([  6,  36,  66,  96, 126, 156, 186])