In [1]:
import numpy as np


In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr=np.arange(0,20,2)

In [5]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr[3]

6

In [8]:
arr[1:5]

array([2, 4, 6, 8])

In [9]:
arr[0:5]=100

In [10]:
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18])

In [11]:
slice_of_arr=arr[0:6]

In [12]:
slice_of_arr

array([100, 100, 100, 100, 100,  10])

In [13]:
slice_of_arr[:]=5


In [14]:
slice_of_arr

array([5, 5, 5, 5, 5, 5])

In [15]:
arr

array([ 5,  5,  5,  5,  5,  5, 12, 14, 16, 18])

In [16]:
arr_copy=arr.copy()

In [17]:
arr.copy

<function ndarray.copy>

In [18]:
arr_2d=np.array([[5,10,15],[12,4,6],[7,8,9]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [12,  4,  6],
       [ 7,  8,  9]])

In [20]:
arr_2d[1]

array([12,  4,  6])

In [21]:
arr_2d[1][0]

12

In [22]:
arr_2d[:2,1:]

array([[10, 15],
       [ 4,  6]])

In [23]:
arr_2d*8

array([[ 40,  80, 120],
       [ 96,  32,  48],
       [ 56,  64,  72]])

In [24]:
arr_2nd[2]

NameError: name 'arr_2nd' is not defined

In [25]:
arr_2d[2]

array([7, 8, 9])

In [28]:
arr2d=np.zeros((10,10))

In [29]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
arr_lenght=arr2d.shape[1]

In [32]:
arr_lenght

10

In [33]:
for i in range(arr_lenght):
    arr2d[i]=1

In [34]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
for i in range(arr_lenght):
    arr2d[i]=i

In [36]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])