In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1=np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1=Series([0,1,2], index=['T','U','V'])
ser2=Series([3,4],index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1=DataFrame(np.random.randn(4,3),columns=['X','Y', 'Z'])
dframe2=DataFrame(np.random.randn(3,3),columns=['A','B', 'C'])

In [14]:
dframe1

X         Y         Z
0 -0.877533 -1.077061  0.289003
1 -0.485080 -0.240529  1.282457
2 -1.276860  0.647532 -1.480258
3  0.457289  1.008531  0.106152

In [15]:
dframe2

A         B         C
0  0.025246 -1.458229  1.428765
1  0.529543 -0.476745 -1.099502
2 -0.280704  0.122019  0.628824

In [16]:
pd.concat([dframe1,dframe2])

X         Y         Z         A         B         C
0 -0.877533 -1.077061  0.289003       NaN       NaN       NaN
1 -0.485080 -0.240529  1.282457       NaN       NaN       NaN
2 -1.276860  0.647532 -1.480258       NaN       NaN       NaN
3  0.457289  1.008531  0.106152       NaN       NaN       NaN
0       NaN       NaN       NaN  0.025246 -1.458229  1.428765
1       NaN       NaN       NaN  0.529543 -0.476745 -1.099502
2       NaN       NaN       NaN -0.280704  0.122019  0.628824

In [17]:
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         A         B         C
0 -0.877533 -1.077061  0.289003       NaN       NaN       NaN
1 -0.485080 -0.240529  1.282457       NaN       NaN       NaN
2 -1.276860  0.647532 -1.480258       NaN       NaN       NaN
3  0.457289  1.008531  0.106152       NaN       NaN       NaN
4       NaN       NaN       NaN  0.025246 -1.458229  1.428765
5       NaN       NaN       NaN  0.529543 -0.476745 -1.099502
6       NaN       NaN       NaN -0.280704  0.122019  0.628824