In [1]:
import numpy as np

In [3]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A=np.random.rand(10)
A

array([0.2665158 , 0.66128272, 0.656582  , 0.04157253, 0.07998201,
       0.04720401, 0.17777119, 0.7777277 , 0.70034233, 0.94354376])

In [8]:
B=np.random.rand(10)
B

array([0.96927464, 0.93982766, 0.23160846, 0.31580445, 0.50062863,
       0.05595578, 0.17964773, 0.34396941, 0.16137763, 0.33531006])

In [9]:
np.add(A,B)

array([1.23579045, 1.60111039, 0.88819046, 0.35737698, 0.58061064,
       0.10315979, 0.35741891, 1.12169711, 0.86171996, 1.27885382])

In [10]:
np.maximum(A,B)

array([0.96927464, 0.93982766, 0.656582  , 0.31580445, 0.50062863,
       0.05595578, 0.17964773, 0.7777277 , 0.70034233, 0.94354376])

In [13]:
website='www.google.com'
import webbrowser
webbrowser.open(website)

True

In [12]:
True

True